[global]
port = 720
dbPrefix = "romiChan"
lang = "zh_CN"
commandPrefix = "/"
dirs = []
noColor = false
level = 20

[adapter.cmd-test]
extends = "cmd"
master = 2333
nickname = "Kotarou"
age = 18
sex = "male"
self-id = 720

[plugin.helper]
content = "test menu"
