[global]
port = 720
dbPrefix = "romiChan"
lang = "zh_CN"
commandPrefix = "/"
dirs = ["modules", "node_modules", "node_modules/@kotori-bot"]
noColor = false
level = 20

[adapter.cmd-test]
extends = "cmd"
master = 2333
nickname = "Kotarou"
age = 18
sex = "male"
self-id = 720

[plugin.helper]
content = "test menu"

[build]
banner = "/**\n* @Package %name%\n* @Version %version%\n* @Author %author%\n* @License %license%\n* @Date %date%\n*/"
